# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: experiments/page:num # jekyll-paginate > experiments page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: jak87 # jekyll-seo-tag > Owners twitter username
author: Jack Kanarek # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Jack Kanarek # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/  # Removed username
    - https://www.facebook.com/ # Removed username
    - https://www.linkedin.com/in/ # Removed username
    - https://plus.google.com/ # Removed username
    - https://github.com/jak87 # Replaced with my username since I actually have this

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: America/New_York # Timezone for experiments posts and alike

# 5. Collections
collections:
  posts:
    title: Experiments # Needed for Siteleaf
    output: true
    description: "This section contains Jupyter notebooks detailing the downstream analysis of our experiments.
    Our hope is to improve transparency and reproducibility in bioinformatic analysis by making the analyses 
    and their output freely available to the public. In our experience, Jupyter notebookes are one of the easiest 
    ways to quickly and comprehensively display all the information necessary. While these can get a little dense 
    given that most of the code and output is included within the notebook, we hope they help others understand, 
    repeat, critique, or learn from our results." # The post list page content
    #feature_text: <h2>Experiments</h2>
    feature_image: "../assets/Pittsburgh_skyline_panorama_at_night.jpg"
    #feature_image: "/assets/rna_interaction_background.png"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "../assets/Pittsburgh_skyline_panorama_at_night.jpg"
      #image: "/assets/rna_interaction_background.png"

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "Nara Lee Lab" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/pitt_logo.png" # Site logo, also used in jekyll-seo-tag
description: "The Lee lab focuses on the basic biology of non-coding RNA through viral models." # Site description and default description, also used in jekyll-seo-tag
url: "https://naraleelab.github.io/" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/NaraLeeLab/NaraLeeLab.github.io"
email: "jpk90@pitt.edu"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
avatarurl: "https://www.gravatar.com/avatar/8ba84467236cfc9ef7b082adfd27ae74" # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub. Note: the gravatar address is just the MD5 hash of the email address linked to the account
# google_analytics: ''
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site navigation
navigation_header:
  Home: /
  About Us: /about_us/
  Lab Members: /lab_members/
  Publications: /publications/
  Experiments: /experiments/
  Search: /search/
  #Fork Alembic: https://github.com/daviddarnes/alembic

navigation_footer:
  Created by Jack Kanarek: https://github.com/jak87
  using Alembic: https://github.com/daviddarnes/alembic

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  # Twitter: https://twitter.com/DavidDarnes
  # LinkedIn: https://www.linkedin.com/in/daviddarnes
  # Google+: https://plus.google.com/+DavidDarnes
  GitHub: https://github.com/NaraLeeLab
  # link: https://darn.es
  # RSS: /feed.xml

sharing_links: # Appear at the bottom of single experiments posts, uncomment and comment out as desired. Colours set the button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Google+: "#DC4E41"
  # Pinterest: "#BD081C"
  # LinkedIn: "#0077B5"
  # tumblr: "#36465D"
  # Reddit: "#FF4500"
  # Hacker News: "#ff6600"
  # Designer News: "#2D72D9"
  # Email: ""
